must be root

diff --git a/hd/exec/dnstart b/hd/exec/dnstart
--- a/hd/exec/dnstart
+++ b/hd/exec/dnstart
@@ -18,6 +18,11 @@
 # limitations under the License.
 #
 
+if [ `id -u` -ne 0 ] ; then
+    echo "!!! ERROR !!! must be root... exit"
+    exit 1
+fi
+
 if [ -z "$JAVA_HOME" ] ; then
     echo "!!! ERROR !!! JAVA_HOME not set... exit"
     exit 1
@@ -37,6 +42,6 @@ export HADOOP_LOG_DIR
 HADOOP_PID_DIR=/tmp
 export HADOOP_PID_DIR
 
-sudo $HADOOP_HOME/sbin/hadoop-daemon.sh --script hdfs start datanode || exit 1
+$HADOOP_HOME/sbin/hadoop-daemon.sh --script hdfs start datanode || exit 1
 
 exit 0
